import sqlite3
import uuid
import time
import os
import logging

logger = logging.getLogger(__name__)

DB_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "memory.db")


class Memory:
    """Three-layer memory: working (context), episodic (SQLite), semantic (ChromaDB)."""

    def __init__(self, db_path=None):
        self.db_path = db_path or DB_PATH
        self.db = sqlite3.connect(self.db_path, check_same_thread=False)
        self.db.execute("PRAGMA journal_mode=WAL")
        self._init_tables()

        self._chroma = None
        self._collection = None

    def _init_tables(self):
        # Create tables if not exist
        self.db.executescript("""
            CREATE TABLE IF NOT EXISTS memories (
                id TEXT PRIMARY KEY,
                type TEXT NOT NULL,
                content TEXT NOT NULL,
                importance REAL DEFAULT 0.5,
                confidence TEXT DEFAULT 'inferred',
                timestamp REAL NOT NULL
            );
            CREATE TABLE IF NOT EXISTS identity (
                key TEXT PRIMARY KEY,
                value TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS conversations (
                id TEXT PRIMARY KEY,
                role TEXT NOT NULL,
                content TEXT NOT NULL,
                timestamp REAL NOT NULL
            );
            CREATE INDEX IF NOT EXISTS idx_memories_type ON memories(type);
            CREATE INDEX IF NOT EXISTS idx_memories_timestamp ON memories(timestamp DESC);
        """)

        # Add confidence column if it doesn't exist (migration for existing databases)
        try:
            self.db.execute(
                "ALTER TABLE memories ADD COLUMN confidence TEXT DEFAULT 'inferred'"
            )
            self.db.commit()
        except sqlite3.OperationalError:
            pass  # Column already exists

        # Add confidence index if it doesn't exist
        try:
            self.db.execute(
                "CREATE INDEX IF NOT EXISTS idx_memories_confidence ON memories(confidence)"
            )
            self.db.commit()
        except sqlite3.OperationalError:
            pass  # Index already exists
        self.db.commit()

    @property
    def collection(self):
        if self._collection is None:
            try:
                import chromadb

                chroma_path = os.path.join(os.path.dirname(self.db_path), "chroma_db")
                client = chromadb.PersistentClient(path=chroma_path)
                self._collection = client.get_or_create_collection(
                    name="soul_memories",
                    metadata={"hnsw:space": "cosine"},
                )
            except Exception as e:
                logger.warning(f"ChromaDB unavailable: {e}. Semantic search disabled.")
                self._collection = None
        return self._collection

    def store(self, memory_type, content, importance=0.5, confidence="inferred"):
        """Store a memory with confidence level.

        Confidence levels:
        - 'verified': From web search or user confirmation
        - 'inferred': Generated by the model without verification
        - 'user': Direct user input
        """
        mem_id = str(uuid.uuid4())
        timestamp = time.time()

        self.db.execute(
            "INSERT INTO memories VALUES (?, ?, ?, ?, ?, ?)",
            (mem_id, memory_type, content, importance, confidence, timestamp),
        )
        self.db.commit()

        # Semantic embedding
        if self.collection is not None:
            try:
                from soul.ollama_client import embed

                embedding = embed(content)
                self.collection.add(
                    ids=[mem_id],
                    embeddings=[embedding],
                    documents=[content],
                    metadatas=[
                        {
                            "type": memory_type,
                            "importance": importance,
                            "confidence": confidence,
                        }
                    ],
                )
            except Exception as e:
                logger.debug(f"Embedding failed: {e}")

        return mem_id

    def recall(self, query, n=5, memory_type=None):
        memories = []

        # Semantic search
        if self.collection is not None:
            try:
                from soul.ollama_client import embed

                embedding = embed(query)

                where = {"type": memory_type} if memory_type else None
                results = self.collection.query(
                    query_embeddings=[embedding], n_results=n, where=where
                )
                if results["documents"] and results["documents"][0]:
                    memories.extend(results["documents"][0])
            except Exception as e:
                logger.debug(f"Semantic recall failed: {e}")

        # Fallback: SQLite
        if not memories:
            if memory_type:
                cur = self.db.execute(
                    "SELECT content FROM memories WHERE type=? ORDER BY importance DESC, timestamp DESC LIMIT ?",
                    (memory_type, n),
                )
            else:
                cur = self.db.execute(
                    "SELECT content FROM memories ORDER BY importance DESC, timestamp DESC LIMIT ?",
                    (n,),
                )
            memories = [row[0] for row in cur.fetchall()]

        return memories

    def store_conversation(self, role, content):
        conv_id = str(uuid.uuid4())
        self.db.execute(
            "INSERT INTO conversations VALUES (?, ?, ?, ?)",
            (conv_id, role, content, time.time()),
        )
        self.db.commit()

    def get_recent_conversation(self, n=10):
        cur = self.db.execute(
            "SELECT role, content FROM conversations ORDER BY timestamp DESC LIMIT ?",
            (n,),
        )
        rows = cur.fetchall()
        return [{"role": r, "content": c} for r, c in reversed(rows)]

    def get_identity(self, key, default=None):
        cur = self.db.execute("SELECT value FROM identity WHERE key=?", (key,))
        row = cur.fetchone()
        return row[0] if row else default

    def set_identity(self, key, value):
        self.db.execute("INSERT OR REPLACE INTO identity VALUES (?, ?)", (key, value))
        self.db.commit()

    def count(self):
        cur = self.db.execute("SELECT COUNT(*) FROM memories")
        return cur.fetchone()[0]

    def close(self):
        self.db.close()
