from .edge_detection import EdgeDetection
from .contour_integration import ContourIntegration
from .form_processing import FormProcessing
from .color_processing import ColorProcessing
from .motion_detection import MotionDetection
from .three_d_structure import ThreeDStructure
from .object_recognition_vis import ObjectRecognitionVis
from .face_recognition import FaceRecognition
from .fine_detail import FineDetail
from .texture_vis import TextureVis
from .scene_recognition import SceneRecognition
from .what_pathway import WhatPathway
